name: NuGet Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'QueryKit/*.csproj'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Restore NuGet Packages
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Get Version
        id: get_version
        run: echo "version=$(cat QueryKit/*.csproj | grep -Eo '<Version>([0-9]+\.){2}[0-9]+<\/Version>' | grep -Eo '([0-9]+\.){2}[0-9]+')" >> $GITHUB_ENV

      - name: Set default version_changed
        run: echo "version_changed=false" >> $GITHUB_ENV
    
      - name: Check for Version Changes
        run: |
          git fetch origin main
          VERSION_CHANGED=$(git diff origin/main HEAD --name-only -- 'QueryKit/*.csproj' | xargs -I{} grep -Eo '<Version>([0-9]+\.){2}[0-9]+<\/Version>' {} | grep -Eo '([0-9]+\.){2}[0-9]+')
          if [ -n "$VERSION_CHANGED" ]; then
            echo "version_changed=true" >> $GITHUB_ENV
          else
            echo "No version changes in QueryKit.csproj file. Skipping deployment."
          fi

      - name: Publish NuGet Package
        if: env.version_changed == 'true'
        run: |
          dotnet pack --configuration Release --no-restore --no-build --output ./nupkgs
          dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY_QUERYKIT }} --source https://api.nuget.org/v3/index.json
