name: NuGet Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Restore NuGet Packages
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Get Version
        id: get_version
        run: echo "::set-output name=version::$(dotnet list package | grep -Eo '([0-9]+\.){2}[0-9]+')"

      - name: Check for Version Changes
        id: version_changed
        run: |
          if [ "${{ github.event_name }}" = "push" ] && git diff --quiet HEAD~1 HEAD -- QueryKit.csproj; then
            echo "No changes to QueryKit.csproj file. Skipping deployment."
            exit 0
          fi

      - name: Publish NuGet Package
        if: steps.version_changed.outputs.version != ''
        env:
          NUGET_API_KEY_QUERYKIT: ${{ secrets.NUGET_API_KEY_QUERYKIT }}
        run: dotnet nuget push ./QueryKit/bin/Release/*.nupkg --api-key $NUGET_API_KEY_QUERYKIT --source https://api.nuget.org/v3/index.json
